set (GBE_HEADERS ${GBE_HEADERS}
    ${CMAKE_CURRENT_LIST_DIR}/Memory.h
    ${CMAKE_CURRENT_LIST_DIR}/MemoryMap.h
    ${CMAKE_CURRENT_LIST_DIR}/MemoryArea.h
    ${CMAKE_CURRENT_LIST_DIR}/Ram.h
)

set(GBE_SOURCES ${GBE_SOURCES}
    ${CMAKE_CURRENT_LIST_DIR}/Memory.cpp
    ${CMAKE_CURRENT_LIST_DIR}/MemoryMap.cpp
    ${CMAKE_CURRENT_LIST_DIR}/MemoryArea.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Ram.cpp
)
